version: '3.4'

services:
  repart.services.formations:
    image: ${DOCKER_REGISTRY}repartservicesformations
    build:
      context: .
      dockerfile: Repart.Services.Formations\Dockerfile

  repart.services.identity:
    image: ${DOCKER_REGISTRY}repartservicesidentity
    build:
      context: .
      dockerfile: Repart.Services.Identity\Dockerfile

